# GitCommitStamp.cmake -- run at BUILD time (via a custom command) to stamp the current git short
# commit hash into a generated header. Writing the header only when the hash actually changes keeps
# the build incremental: an unchanged commit leaves the file's mtime untouched, so WorldBuilder.cpp
# is not needlessly recompiled, but a new commit refreshes it before the next compile.
#
# Expects: -DGIT_EXECUTABLE=<git> -DSRC_DIR=<repo dir> -DOUT_FILE=<generated header path>

set(_commit "unknown")
if(GIT_EXECUTABLE)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" rev-parse --short HEAD
        WORKING_DIRECTORY "${SRC_DIR}"
        OUTPUT_VARIABLE _git_commit
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET)
    if(_git_commit)
        set(_commit "${_git_commit}")
    endif()
endif()

set(_content "// Generated by GitCommitStamp.cmake at build time -- do not edit.\n#define WB_BUILD_COMMIT \"${_commit}\"\n")

set(_existing "")
if(EXISTS "${OUT_FILE}")
    file(READ "${OUT_FILE}" _existing)
endif()

if(NOT _existing STREQUAL _content)
    file(WRITE "${OUT_FILE}" "${_content}")
endif()
