/*
**	Command & Conquer Generals Zero Hour(tm)
**	Copyright 2025 Electronic Arts Inc.
**
**	This program is free software: you can redistribute it and/or modify
**	it under the terms of the GNU General Public License as published by
**	the Free Software Foundation, either version 3 of the License, or
**	(at your option) any later version.
**
**	This program is distributed in the hope that it will be useful,
**	but WITHOUT ANY WARRANTY; without even the implied warranty of
**	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**	GNU General Public License for more details.
**
**	You should have received a copy of the GNU General Public License
**	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

// FILE: W3DEmbeddedShaders.h /////////////////////////////////////////////////////////////////////

#pragma once

#include "Lib/BaseType.h"

#include <windows.h>

// One fxc-built shader linked into the executable.
struct EmbeddedShader
{
	const char *name;
	const unsigned char *data;
	unsigned int size;
};

// Generated by cmake/embed_shaders.cmake, sorted by lowercase name, with a null entry last so an empty table compiles.
extern const EmbeddedShader TheEmbeddedShaders[];
extern const unsigned int TheEmbeddedShaderCount;

/// Finds a linked-in shader by its "shaders\<file>" path, in any case and with either slash.
Bool Find_Embedded_Shader(const char *path, const void *&data, DWORD &size);
